//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTool.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexTool.Core.Properties.FormStrings", typeof(FormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string STR_ABOUT {
            get {
                return ResourceManager.GetString("STR_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat digit string as numbers for sort.
        /// </summary>
        internal static string STR_BTN_ALLOW_DIGIT_2_NUM {
            get {
                return ResourceManager.GetString("STR_BTN_ALLOW_DIGIT_2_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string STR_BTN_CLEAR {
            get {
                return ResourceManager.GetString("STR_BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string STR_BTN_COLLAPSE {
            get {
                return ResourceManager.GetString("STR_BTN_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show duplicated only.
        /// </summary>
        internal static string STR_BTN_DUPLICATED_ONLY {
            get {
                return ResourceManager.GetString("STR_BTN_DUPLICATED_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expend.
        /// </summary>
        internal static string STR_BTN_EXPEND {
            get {
                return ResourceManager.GetString("STR_BTN_EXPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingore duplicated.
        /// </summary>
        internal static string STR_BTN_INGORE_DUPLICATED {
            get {
                return ResourceManager.GetString("STR_BTN_INGORE_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string STR_BTN_SEARCH {
            get {
                return ResourceManager.GetString("STR_BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Project.
        /// </summary>
        internal static string STR_CLOSE_PROJECT {
            get {
                return ResourceManager.GetString("STR_CLOSE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string STR_EXIT {
            get {
                return ResourceManager.GetString("STR_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string STR_HOMEPAGE {
            get {
                return ResourceManager.GetString("STR_HOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length: {0}.
        /// </summary>
        internal static string STR_INPUT_LEN {
            get {
                return ResourceManager.GetString("STR_INPUT_LEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow empty replace pattern.
        /// </summary>
        internal static string STR_LBL_ALLOW_EMPTY_REPLACE {
            get {
                return ResourceManager.GetString("STR_LBL_ALLOW_EMPTY_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Separator:.
        /// </summary>
        internal static string STR_LBL_BATCH_SEPARATOR {
            get {
                return ResourceManager.GetString("STR_LBL_BATCH_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        internal static string STR_LBL_FILTER {
            get {
                return ResourceManager.GetString("STR_LBL_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string STR_LBL_LOAD {
            get {
                return ResourceManager.GetString("STR_LBL_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Pattern:.
        /// </summary>
        internal static string STR_LBL_REPLACE_PATTERN {
            get {
                return ResourceManager.GetString("STR_LBL_REPLACE_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Result:.
        /// </summary>
        internal static string STR_LBL_REPLACE_RESULT {
            get {
                return ResourceManager.GetString("STR_LBL_REPLACE_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        internal static string STR_LBL_TEMPLATE_RESULT {
            get {
                return ResourceManager.GetString("STR_LBL_TEMPLATE_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        internal static string STR_MATCH {
            get {
                return ResourceManager.GetString("STR_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Matches.
        /// </summary>
        internal static string STR_MATCH_INFO {
            get {
                return ResourceManager.GetString("STR_MATCH_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string STR_MENU_DONATE {
            get {
                return ResourceManager.GetString("STR_MENU_DONATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string STR_MENU_HELP {
            get {
                return ResourceManager.GetString("STR_MENU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string STR_MENU_HOME {
            get {
                return ResourceManager.GetString("STR_MENU_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string STR_MENU_ITEM_CLEAR {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string STR_MENU_ITEM_COPY {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All.
        /// </summary>
        internal static string STR_MENU_ITEM_COPY_ALL {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_COPY_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as Regular Expression.
        /// </summary>
        internal static string STR_MENU_ITEM_COPY_AS_REGEX {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_COPY_AS_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string STR_MENU_ITEM_CUT {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string STR_MENU_ITEM_DELETE {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string STR_MENU_ITEM_PASTE {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as Regular Expression input.
        /// </summary>
        internal static string STR_MENU_ITEM_PUT_INTO_REGEX_BOX {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_PUT_INTO_REGEX_BOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string STR_MENU_ITEM_SAVE {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string STR_MENU_ITEM_SELECT_ALL {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match on selection Only.
        /// </summary>
        internal static string STR_MENU_ITEM_SELECTION_ONLY {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_SELECTION_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to source.
        /// </summary>
        internal static string STR_MENU_ITEM_SEND_TO_SOURCE {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_SEND_TO_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format as Regular Expression.
        /// </summary>
        internal static string STR_MENU_ITEM_TO_REGEX_FORMAT {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_TO_REGEX_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string STR_MENU_ITEM_UNDO {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordWrap.
        /// </summary>
        internal static string STR_MENU_ITEM_WORDWRAP {
            get {
                return ResourceManager.GetString("STR_MENU_ITEM_WORDWRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string STR_MENU_LANGUAGE {
            get {
                return ResourceManager.GetString("STR_MENU_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string STR_MENU_MISC {
            get {
                return ResourceManager.GetString("STR_MENU_MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Window.
        /// </summary>
        internal static string STR_MENU_NEW_WINDOW {
            get {
                return ResourceManager.GetString("STR_MENU_NEW_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string STR_MENU_SETTINGS {
            get {
                return ResourceManager.GetString("STR_MENU_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple List Comparer.
        /// </summary>
        internal static string STR_MENU_SIMPLE_COMPARER {
            get {
                return ResourceManager.GetString("STR_MENU_SIMPLE_COMPARER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input regular expression.
        /// </summary>
        internal static string STR_MSG_EMPTY_REGEXEXPRESSION {
            get {
                return ResourceManager.GetString("STR_MSG_EMPTY_REGEXEXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string STR_NEW_PROJECT {
            get {
                return ResourceManager.GetString("STR_NEW_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Document.
        /// </summary>
        internal static string STR_ONLINE_DOC {
            get {
                return ResourceManager.GetString("STR_ONLINE_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Internet Explorer.
        /// </summary>
        internal static string STR_OPEN_BROWSER {
            get {
                return ResourceManager.GetString("STR_OPEN_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Notepad.
        /// </summary>
        internal static string STR_OPEN_NOTEPAD {
            get {
                return ResourceManager.GetString("STR_OPEN_NOTEPAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        internal static string STR_OPEN_PROJECT {
            get {
                return ResourceManager.GetString("STR_OPEN_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string STR_OPTIONS {
            get {
                return ResourceManager.GetString("STR_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        internal static string STR_PAGE_MATCHES {
            get {
                return ResourceManager.GetString("STR_PAGE_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string STR_PAGE_REPLACE {
            get {
                return ResourceManager.GetString("STR_PAGE_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string STR_PAGE_TEMPLATE {
            get {
                return ResourceManager.GetString("STR_PAGE_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not found, do you want to delete the recent file?.
        /// </summary>
        internal static string STR_RECENT_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("STR_RECENT_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        internal static string STR_RECENT_FILES {
            get {
                return ResourceManager.GetString("STR_RECENT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        internal static string STR_RECENT_PROJECTS {
            get {
                return ResourceManager.GetString("STR_RECENT_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        internal static string STR_SAVE_PROJECT {
            get {
                return ResourceManager.GetString("STR_SAVE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string STR_STOP {
            get {
                return ResourceManager.GetString("STR_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text file(*.txt)|*.txt|xml files(*.xml)|*.xml|sql files(*.sql)|*.sql|All file(*.*)|*.*.
        /// </summary>
        internal static string STR_TEXT_SAVE_FILTER {
            get {
                return ResourceManager.GetString("STR_TEXT_SAVE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the items count per batch.
        /// </summary>
        internal static string STR_TIP_ITEMS_PER_BATCH {
            get {
                return ResourceManager.GetString("STR_TIP_ITEMS_PER_BATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by the specific group.
        /// </summary>
        internal static string STR_TIP_ORDER_BY {
            get {
                return ResourceManager.GetString("STR_TIP_ORDER_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        internal static string STR_TITLE_SAVE_PROJECT {
            get {
                return ResourceManager.GetString("STR_TITLE_SAVE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project As ....
        /// </summary>
        internal static string STR_TITLE_SAVE_PROJECT_AS {
            get {
                return ResourceManager.GetString("STR_TITLE_SAVE_PROJECT_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnning.
        /// </summary>
        internal static string STR_TITLE_WARNNING {
            get {
                return ResourceManager.GetString("STR_TITLE_WARNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture {0}: {1}.
        /// </summary>
        internal static string STR_TREEVIEW_NODE_CAPTURE {
            get {
                return ResourceManager.GetString("STR_TREEVIEW_NODE_CAPTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0}: {1}.
        /// </summary>
        internal static string STR_TREEVIEW_NODE_GROUP {
            get {
                return ResourceManager.GetString("STR_TREEVIEW_NODE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match-{0}: {1}.
        /// </summary>
        internal static string STR_TREEVIEW_NODE_MATCH {
            get {
                return ResourceManager.GetString("STR_TREEVIEW_NODE_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Project.
        /// </summary>
        internal static string STR_UNTITLED_PROJECT {
            get {
                return ResourceManager.GetString("STR_UNTITLED_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regular expression.
        /// </summary>
        internal static string TIP_CB_FILTER_AS_REGEX {
            get {
                return ResourceManager.GetString("TIP_CB_FILTER_AS_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match whole.
        /// </summary>
        internal static string TIP_CB_FILTER_WHOLEWORD {
            get {
                return ResourceManager.GetString("TIP_CB_FILTER_WHOLEWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any (0 or more). Press ALT for *?.
        /// </summary>
        internal static string TIP_REGEX_ANY {
            get {
                return ResourceManager.GetString("TIP_REGEX_ANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can click it with Shift, Ctrl or Alt key..
        /// </summary>
        internal static string TIP_REGEX_BORDER {
            get {
                return ResourceManager.GetString("TIP_REGEX_BORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character group, right click to define any single character that is not in character_group. By default, characters in character_group are case-sensitive..
        /// </summary>
        internal static string TIP_REGEX_CHAR_GROUP {
            get {
                return ResourceManager.GetString("TIP_REGEX_CHAR_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches any decimal digit. Press Ctrl for \d+, Shift for \d*, Alt for \d?.
        /// </summary>
        internal static string TIP_REGEX_DIGIT {
            get {
                return ResourceManager.GetString("TIP_REGEX_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group the selected text. Right click to define an uncapturing group..
        /// </summary>
        internal static string TIP_REGEX_GROUP {
            get {
                return ResourceManager.GetString("TIP_REGEX_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches the previous element exactly m times: {m}, or not more than n {m,n}..
        /// </summary>
        internal static string TIP_REGEX_M_TIMES {
            get {
                return ResourceManager.GetString("TIP_REGEX_M_TIMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many (1 or more). Press ALT for +?.
        /// </summary>
        internal static string TIP_REGEX_MANY {
            get {
                return ResourceManager.GetString("TIP_REGEX_MANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 or 1.
        /// </summary>
        internal static string TIP_REGEX_NONE_OR_ONE {
            get {
                return ResourceManager.GetString("TIP_REGEX_NONE_OR_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Document about Regular Expressions.
        /// </summary>
        internal static string TIP_REGEX_ONELINE_DOC {
            get {
                return ResourceManager.GetString("TIP_REGEX_ONELINE_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches any one element separated by the vertical bar (|) character. For example: th(e|is|at).
        /// </summary>
        internal static string TIP_REGEX_OR {
            get {
                return ResourceManager.GetString("TIP_REGEX_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match a new line. You can click it with Shift, Ctrl or Alt key..
        /// </summary>
        internal static string TIP_REGEX_RETURN {
            get {
                return ResourceManager.GetString("TIP_REGEX_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches any white-space character. Press Ctrl for \s+, Shift for \s*, Alt for \s?.
        /// </summary>
        internal static string TIP_REGEX_SPACE {
            get {
                return ResourceManager.GetString("TIP_REGEX_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match must start at the beginning of the string or line. Right click for $, The match must occur at the end of the string or before \n at the end of the line or string..
        /// </summary>
        internal static string TIP_REGEX_START {
            get {
                return ResourceManager.GetString("TIP_REGEX_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match a tab. You can click it with Shift, Ctrl or Alt key..
        /// </summary>
        internal static string TIP_REGEX_TAB {
            get {
                return ResourceManager.GetString("TIP_REGEX_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard: Matches any single character except \n. To match a literal period character (. or \u002E), you must precede it with the escape character (\.)..
        /// </summary>
        internal static string TIP_REGEX_WILDCARD {
            get {
                return ResourceManager.GetString("TIP_REGEX_WILDCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches any word character. Press Ctrl for \w+, Shift for \w*, Alt for \w?.
        /// </summary>
        internal static string TIP_REGEX_WORD {
            get {
                return ResourceManager.GetString("TIP_REGEX_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Number.
        /// </summary>
        internal static string TIP_ROWNUMBER {
            get {
                return ResourceManager.GetString("TIP_ROWNUMBER", resourceCulture);
            }
        }
    }
}
