using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RegexTool.Core
{
    /// <summary>
    /// keys for resources
    /// </summary>
    public enum FormStringKeys
    {
        STR_MENU_ITEM_COPY,
        STR_NEW_PROJECT,
        STR_CLOSE_PROJECT,
        STR_MENU_HOME,
        STR_MENU_MISC,
        STR_MENU_SETTINGS,
        STR_MENU_LANGUAGE,
        STR_MENU_HELP,
        STR_ABOUT,
        STR_OPEN_PROJECT,
        STR_SAVE_PROJECT,
        STR_TITLE_SAVE_PROJECT_AS,
        STR_EXIT,
        STR_HISTORY,
        STR_HOMEPAGE,
        STR_MATCH,
        STR_ONLINE_DOC,
        STR_RECENT_FILES,
        STR_OPEN_NOTEPAD,
        STR_OPEN_BROWSER,
        STR_RECENT_PROJECTS,
        STR_STOP,
        STR_LBL_LOAD,
        STR_PAGE_MATCHES,
        STR_PAGE_REPLACE,
        STR_PAGE_TEMPLATE,
        STR_MENU_ITEM_CUT,
        STR_MENU_ITEM_PASTE,
        STR_MENU_ITEM_COPY_ALL,
        STR_MENU_ITEM_SAVE,
        STR_MENU_ITEM_WORDWRAP,
        STR_MENU_ITEM_SELECT_ALL,
        STR_MENU_ITEM_CLEAR,
        STR_MENU_ITEM_SEND_TO_SOURCE,
        STR_MENU_ITEM_UNDO,
        STR_MENU_ITEM_COPY_AS_REGEX,
        STR_MENU_ITEM_SELECTION_ONLY,
        STR_MENU_ITEM_TO_REGEX_FORMAT,
        STR_MENU_ITEM_DELETE,
        STR_MENU_ITEM_PUT_INTO_REGEX_BOX,
        STR_LBL_FILTER,
        STR_BTN_SEARCH,
        STR_BTN_CLEAR,
        STR_BTN_COLLAPSE,
        STR_BTN_EXPEND,
        STR_LBL_REPLACE_PATTERN,
        STR_LBL_ALLOW_EMPTY_REPLACE,
        STR_LBL_REPLACE_RESULT,
        STR_LBL_TEMPLATE_RESULT,
        STR_LBL_BATCH_SEPARATOR,
        STR_OPTIONS,
        STR_BTN_INGORE_DUPLICATED,
        STR_BTN_DUPLICATED_ONLY,
        STR_BTN_ALLOW_DIGIT_2_NUM,
        STR_TIP_ORDER_BY,
        STR_TIP_ITEMS_PER_BATCH,
        STR_TREEVIEW_NODE_MATCH,
        STR_TREEVIEW_NODE_GROUP,
        STR_TREEVIEW_NODE_CAPTURE,
        STR_MATCH_INFO,
        TIP_REGEX_START,
        TIP_REGEX_DIGIT,
        TIP_REGEX_WORD,
        TIP_REGEX_SPACE,
        TIP_REGEX_TAB,
        TIP_REGEX_BORDER,
        TIP_REGEX_WILDCARD,
        TIP_REGEX_RETURN,
        TIP_REGEX_MANY,
        TIP_REGEX_NONE_OR_ONE,
        TIP_REGEX_M_TIMES,
        TIP_REGEX_OR,
        TIP_REGEX_GROUP,
        TIP_REGEX_CHAR_GROUP,
        TIP_REGEX_ONELINE_DOC,
        TIP_REGEX_ANY,
        STR_MENU_DONATE,
        TIP_CB_FILTER_AS_REGEX,
        TIP_CB_FILTER_WHOLEWORD,
        STR_UNTITLED_PROJECT,
        STR_MSG_EMPTY_REGEXEXPRESSION,
        STR_TITLE_WARNNING,
        STR_RECENT_FILE_NOT_FOUND,
        STR_TEXT_SAVE_FILTER,
        STR_TITLE_SAVE_PROJECT,
        STR_MENU_NEW_WINDOW,
        STR_MENU_SIMPLE_COMPARER,
        /// <summary>
        /// Row Number in Template Page
        /// </summary>
        TIP_ROWNUMBER,
    }
}
